name: Deploy
on:
  push:
    branches: [beta-*]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-deploy-beta
  cancel-in-progress: false
jobs:
  deploy-package-next:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: package
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          # NOTE(krishan711): need full history to calculate difference
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          cache-from: type=gha,scope=package
          cache-to: type=gha,mode=max,scope=package
          tags: ${{ env.DOCKER_IMAGE }}
      - name: Calculate commit count since last tag
        id: vars
        run: echo ::set-output name=commit_count::$(git rev-list $(git describe --tags --abbrev=0)..HEAD --count)
      - name: Create .npmrc file
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - name: Publish next package to npm
        if: steps.vars.outputs.commit_count != '0'
        run: docker run -v $(pwd)/.npmrc:/root/.npmrc $DOCKER_IMAGE make NEXT_VERSION=${{ steps.vars.outputs.commit_count }} NEXT_TYPE=${{ github.ref_name }} publish-next
  